Document: dnssec-validator
Title: Debian dnssec-validator Manual
Author: <insert document author here>
Abstract: This manual describes what dnssec-validator is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dnssec-validator/dnssec-validator.sgml.gz

Format: postscript
Files: /usr/share/doc/dnssec-validator/dnssec-validator.ps.gz

Format: text
Files: /usr/share/doc/dnssec-validator/dnssec-validator.text.gz

Format: HTML
Index: /usr/share/doc/dnssec-validator/html/index.html
Files: /usr/share/doc/dnssec-validator/html/*.html
